function importTracks = chemotaxisToolImport(tracks)

% Raw tracks data must be imported into the Chemotaxis and Migration Tool 
% as a tab-deliminated format ASCII file containing five columns.
% All numbers must be whole numbers requiring that the tracks output be
% rounded to obtain an interger value.  This should not have any pronounced
% affect on computed statistics.

% INPUT: 
% 
%        tracks: tracks matrix generated by track.m
%        column1: x-position
%        column2: y-position
%        column3: frame
%        column4: track number

% Output:
%
%        chemotax_tool: tab-deliminated file exported to the current folder
%        col1: Consequtive numbers
%        col2: track number
%        col3: frame 
%        col4: x-postion
%        col5: y-position

m = 1:size(tracks,1);

importTracks = [m', tracks(:,4), tracks(:,3), tracks(:,1), tracks(:,2)];
importTracks = round(importTracks);
dlmwrite('chemotax_tool.txt', importTracks, 'delimiter', '\t')