function trax = number_first_traxID_one(tracks)
%
% NAME:
%       number_first_traxID_one
% PURPOSE:
%       sequentially number track IDs from tracks matrix 
%               
%
% INPUTS:
%       tracks: tracks matrix generated by track.m
%        column1: x-position
%        column2: y-position
%        column3: frame
%        column4: track number
%
% OUTPUTS:
%       trax: tracks matrix with track IDs (column4) sequentialy numbered
%       from 1:N


trax = [];
ID = 1;
cell_num = unique(tracks(:,4));

for i = cell_num'
    
    data = tracks(tracks(:,4) == i, :);
    sz = size(data, 1);
    new_id = repmat(ID, sz, 1);
    data = [data(:,1:3), new_id];
    trax = [trax; data];
    ID = ID + 1;

end